### ISSUE TITLE
Contexts persist in `gptel-context--alist` when removed in alternate fashion

### ISSUE THREAD

**Issue by daedsidog** [karthink/gptel#332]
1. Add a context in a buffer
2. Remove the context by invoking `gptel-add` at point
3. `gptel-context--alist` has an empty context, causing bugs later on.

**Comment by karthink** [comment]
Talk about timing, I fixed this 10 minutes ago.

**Comment by karthink** [comment]
Also it doesn't cause any bugs in gptel's request, since this clean-up is done before the request is constructed.  It's only the visual indicators (in the transient menu and now in the chat header too) that can be out of date as a result.

**Comment by daedsidog** [comment]
> Talk about timing, I fixed this 10 minutes ago.

I'm on the latest master and I'm still getting it.

> Also it doesn't cause any bugs in gptel's request, since this clean-up is done before the request is constructed. It's only the visual indicators (in the transient menu and now in the chat header too) that can be out of date as a result.

It does cause bugs when commandeering the context string generation functions, for example.

I really think cleanup should be handled in the removal.

**Comment by karthink** [comment]
> I'm on the latest master and I'm still getting it.

https://github.com/karthink/gptel/blob/master/gptel-context.el#L169

**Comment by karthink** [comment]
> So, outside of commandeering the default string generation functions, is there any risk of the alist being polluted?

What do you mean by polluted?

**Comment by karthink** [comment]
> > I'm on the latest master and I'm still getting it.
> 
> https://github.com/karthink/gptel/blob/master/gptel-context.el#L169

This fix is incomplete, I guess I need this check in other places in this function too.

**Comment by daedsidog** [comment]
> What do you mean by polluted?

Removing contexts programmatically leaves you with an alist of the form:

`((#<buffer` main.c> #<overlay in no buffer>))`

In such a case executing `(gptel-context--string gptel-context--alist)` results in an error.

**Comment by karthink** [comment]
> In such a case executing (gptel-context--string gptel-context--alist) results in an error.

Ah, this is what you meant by "commandeering the string generation".  I'll fix it, but it's a low priority for now since doing this the right way (via customizing `gptel-context-wrap-function`) should not cause any issues.

**Comment by karthink** [comment]
Cannot reproduce any more.
